name: build_rpm
on:
  workflow_dispatch:
      inputs:
        ssh:
          description: 'SSH connection to Actions'
          required: true
          default: 'false'
  schedule:
    - cron: 0 10 * * *

env:
  env:
  CONFIG_FILE: newifi_D2.config
  DRIVE_LABLE: newifi_D2
  UPLOAD_RELEASE: true
  UPLOAD_FIRMWARE: true
  UPLOAD_BIN_DIR: false
  REMOVE_OLD_RELEASE: true
  REMOVE_WORKFLOW_RUNS: true
  KERNEL_HASH: 7318552cb8f6798b0a6d707a2f563d94


jobs:     
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        sudo apt remove php* dotnet* google* 
        docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
 
    - name: run-centos
      run: |
        cd
        mkdir rpm
        centos=`docker run -itd -v rpm:/root centos:7`
        echo "export centos=$centos" >> .profile
        docker exec -itd $centos /bin/bash
        yum install epel-release wget curl rpm-build rpmdevtools -y
        rpmdev-setuptree
        
    - name: init-build
      run: |
        echo "1111"

    - name: Start SSH via ngrok
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        # After sign up on the https://ngrok.com
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        
        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        # You can find this server region here: https://ngrok.com/docs#global-locations
        NGROK_REGION: jp

        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}