name: nezha-rocky9
on:
  workflow_dispatch:
      inputs:
        ssh:
          description: 'SSH connection to Actions'
          required: true
          default: 'false'
  # schedule:
  #   - cron: 0 10 * * *

env:
  VERSION: 1.5.1
  REMOVE_WORKFLOW_RUNS: true

jobs:     
  centos-build-rpms:
    name: centos-build-rpms
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        # sudo apt remove php* dotnet* google* 
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
 
    - name: run-rocky
      # 出错继续
      continue-on-error: true
      run: |
        mkdir rpm
        centos=`docker run -itd -v $(pwd)/rpm:/opt ghcr.io/codetiger666/images/rocky:9`
        echo "export centos=$centos" >> $HOME/.profile
        source $HOME/.profile
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        docker exec -i $centos rpmdev-setuptree
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    # 编译
    - name: build
      run: |
        sudo sed -i "s/codetiger_version/$VERSION/g" specs/nezha-agent.spec
        sudo /bin/cp specs/nezha-agent.spec rpm/rpmbuild/SPECS/nezha-agent.spec
        wget https://github.com/nezhahq/agent/releases/download/v$VERSION/nezha-agent_linux_amd64.zip
        mkdir rpm/rpmbuild/SOURCES -p
        sudo /bin/cp nezha-agent_linux_amd64.zip rpm/rpmbuild/SOURCES
        sudo /bin/cp nezha/nezha-agent.sh rpm/rpmbuild/SOURCES
        sudo /bin/cp nezha/agent.conf rpm/rpmbuild/SOURCES
        sudo /bin/cp services/nezha-agent.service rpm/rpmbuild/SOURCES
        source $HOME/.profile
        docker stop $centos
        docker start $centos
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        docker exec -i $centos rpmbuild -ba /opt/rpmbuild/SPECS/nezha-agent.spec
        
    - name: checkout_rpm
      run: |
        git clone https://github.com/codetiger666/centos_rpms.git

    - name: copy realease
      # 出错继续
      # continue-on-error: true
      run: |
        sudo mkdir -p centos_rpms/rocky/9/x86_64/
        cd centos_rpms
        git pull
        rm -f rocky/9/x86_64/nezha_agent*.x86_64.rpm
        cd ..
        sudo /bin/cp rpm/rpmbuild/RPMS/x86_64/nezha_agent-$VERSION-1.el9.x86_64.rpm centos_rpms/rocky/9/x86_64/
        rpms=`docker run -itd -v $(pwd)/centos_rpms:/centos_rpms ghcr.io/codetiger666/images/rocky:9`
        docker exec -i $rpms createrepo /centos_rpms/rocky/9/x86_64/

    - name: git add
      working-directory: ./centos_rpms
      run: |
        git pull
        git config --local user.email ${{ secrets.email }}
        git config --local user.name "codetiger666"
        # 创建一个新的孤立分支
        git checkout --orphan temp_main
        # 添加所有文件并进行提交
        git add -A
        git commit -m "update"
        # 删除旧的 main 分支并将新分支重命名为 main
        git branch -D main
        git branch -m main
        git remote set-url origin https://${{ secrets.GITHUBTOKEN }}@github.com/codetiger666/centos_rpms.git
        git push -f origin main

    
    - name: Remove workflow runs
      uses: GitRML/delete-workflow-runs@main
      if: env.REMOVE_WORKFLOW_RUNS == 'true' && !cancelled()
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: SSH connection to Actions 1
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
