name: onedrive-rocky9-arm
on:
  workflow_dispatch:
      inputs:
        ssh:
          description: 'SSH connection to Actions'
          required: true
          default: 'false'
  # schedule:
  #   - cron: 0 10 * * *

env:
  VERSION: 2.5.0-rc3
  REMOVE_WORKFLOW_RUNS: true

jobs:     
  centos-build-rpms:
    name: centos-build-rpms
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        # sudo apt remove php* dotnet* google* 
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
 
    - name: run-rocky
      # 出错继续
      continue-on-error: true
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
        mkdir rpm
        wget https://github.com/multiarch/qemu-user-static/releases/download/v7.2.0-1/qemu-aarch64-static
        chmod +x qemu-aarch64-static
        centos=`docker run -itd -v $(pwd)/rpm:/opt --platform arm64 -v $(pwd)/qemu-aarch64-static:/usr/bin/qemu-aarch64-static rockylinux:9`
        echo "export centos=$centos" >> $HOME/.profile
        source $HOME/.profile
        docker exec -i $centos dnf install wget -y
        docker exec -i $centos rm -rf /etc/yum.repos.d
        docker exec -i $centos mkdir /etc/yum.repos.d
        docker exec -i $centos wget -P /etc/yum.repos.d/ https://raw.githubusercontent.com/codetiger666/linux/master/scripts/linux/rocky/rocky.repo
        docker exec -i $centos dnf install -y pcre-devel ldc libevent-devel sqlite-devel net-snmp-devel mysql-community-client mysql-community-common mysql-community-devel mysql-community-libs rpmdevtools libssh2-devel OpenIPMI-devel openssl-devel libxslt* perl-ExtUtils-Embed gcc-c++ python subversion gperf make rpm-build git curl bzip2-devel libcurl-devel gd gd-devel  libtidy libtidy-devel GeoIP-devel libatomic_ops-devel zlib-devel unzip libstdc++* net-snmp-utils gmp gmp-devel gmp gmp-devel openldap openldap-devel libpcap-devel glib2-devel GeoIP-devel libxml2-devel libxml2-devel vim wget automake mlocate openssl-devel pam-devel unzip gcc screen openssl openssl-devel bash-completion* pcre-devel libxslt* perl-ExtUtils-Embed gcc-c++ --skip-broken
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        docker exec -i $centos rpmdev-setuptree
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    # 编译
    - name: build
      run: |
        sudo sed -i "s/codetiger_version/$VERSION/g" specs/onedrive.spec
        sudo /bin/cp specs/onedrive.spec rpm/rpmbuild/SPECS/onedrive.spec
        wget https://github.com/abraunegg/onedrive/archive/refs/tags/v$VERSION.tar.gz
        mkdir rpm/rpmbuild/SOURCES -p
        sudo /bin/cp v$VERSION.tar.gz rpm/rpmbuild/SOURCES/onedrive-$VERSION.tar.gz
        sudo /bin/cp onedrive/config rpm/rpmbuild/SOURCES
        sudo /bin/cp onedrive/onedrive rpm/rpmbuild/SOURCES
        sudo /bin/cp services/onedrive.service rpm/rpmbuild/SOURCES
        source $HOME/.profile
        docker stop $centos
        docker start $centos
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        docker exec -i $centos rpmbuild -ba /opt/rpmbuild/SPECS/onedrive.spec
        
    - name: checkout_rpm
      run: |
        git clone https://github.com/codetiger666/centos_rpms.git

    - name: copy realease
      # 出错继续
      # continue-on-error: true
      run: |
        sudo mkdir -p centos_rpms/rocky/9/aarch64/
        cd centos_rpms
        git pull
        rm -f rocky/9/aarch64/onedirve*.aarch64.rpm
        cd ..
        sudo /bin/cp rpm/rpmbuild/RPMS/aarch64/onedrive-$VERSION-1.el9.aarch64.rpm centos_rpms/rocky/9/aarch64/
        rpms=`docker run -itd -v $(pwd)/centos_rpms:/centos_rpms --platform arm64 -v $(pwd)/qemu-aarch64-static:/usr/bin/qemu-aarch64-static rockylinux:9`
        docker exec -i $rpms dnf install createrepo -y
        docker exec -i $rpms createrepo /centos_rpms/rocky/9/aarch64/

    - name: git add
      working-directory: ./centos_rpms
      run: |
        git pull
        git config --local user.email ${{ secrets.email }}
        git config --local user.name "codetiger666"
        git add ./
        git commit -m "update onedrive arm64"
        git pull

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     directory: ./centos_rpms
    #     repository: codetiger666/centos_rpms
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: main
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUBTOKEN }}
      with:
        source-directory: 'centos_rpms'
        destination-github-username: 'codetiger666'
        destination-repository-name: 'centos_rpms'
        user-email: ${{ secrets.email }}
        target-branch: main
    
    - name: Remove workflow runs
      uses: GitRML/delete-workflow-runs@main
      if: env.REMOVE_WORKFLOW_RUNS == 'true' && !cancelled()
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: SSH connection to Actions 1
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
