name: release
on:
  workflow_dispatch:
      inputs:
        program:
          description: '软件名称'
          required: true
          type: choice
          options:
            - openresty
            - nezha-agent
            - onedrive
            - openssh-server
            - frp
        version:
          description: '软件版本'
          required: true
          default: '1.0'
        release:
          description: '系统版本'
          required: true
          default: '9'
          type: choice
          options:
            - 9
            - 7
        remove:
          description: '是否删除历史版本'
          required: false
          default: 'true'
          type: choice
          options:
            - 'true'
            - 'false'
        arch:
          description: '架构'
          required: true
          default: 'x86_64'
          type: choice
          options:
            - x86_64
            - aarch64
        ssh:
          description: '是否开启ssh调试'
          required: true
          default: 'false'
          type: choice
          options:
            - 'true'
            - 'false'

env:
  REMOVE_WORKFLOW_RUNS: true

jobs:     
  centos-build-rpms:
    name: build-rpms-${{ github.event.inputs.program }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        # sudo apt remove php* dotnet* google* 
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php

    # 初始化环境变量
    - name: init-env
      run: |
        echo "export project_program=${{ github.event.inputs.program }}" >> $HOME/.profile
        echo "export project_version=${{ github.event.inputs.version }}" >> $HOME/.profile
        echo "export project_arch=${{ github.event.inputs.arch }}" >> $HOME/.profile
        source $HOME/.profile
 
    - name: run-rocky
      # 出错继续
      continue-on-error: true
      run: |
        mkdir rpm
        case ${{ github.event.inputs.arch }} in
          aarch64)
            echo "使用arm64编译"
            docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
            wget https://github.com/multiarch/qemu-user-static/releases/download/v7.2.0-1/qemu-aarch64-static
            chmod +x qemu-aarch64-static
            centos=`docker run -itd -v $(pwd)/rpm:/opt --platform arm64 -v $(pwd)/qemu-aarch64-static:/usr/bin/qemu-aarch64-static ghcr.io/codetiger666/images/rocky:9`
            ;;
          x86_64)
            echo "使用x86编译"
            centos=`docker run -itd -v $(pwd)/rpm:/opt ghcr.io/codetiger666/images/rocky:9`
            ;;
          *)
            echo "未知架构，请检查"
            exit 0
            ;;
        esac
        echo "export centos=$centos" >> $HOME/.profile
        source $HOME/.profile
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        docker exec -i $centos rpmdev-setuptree
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros

    - name: init
      run: |
        source $HOME/.profile
        if [ -f "./scripts/${{ github.event.inputs.program }}.sh" ];
        then
          source ./scripts/${{ github.event.inputs.program }}.sh
          program_init
        fi
        sudo /bin/cp specs/${{ github.event.inputs.program }}.spec rpm/rpmbuild/SPECS/${{ github.event.inputs.program }}.spec

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    # 编译
    - name: build
      run: |
        source $HOME/.profile
        docker stop $centos
        docker start $centos
        docker cp $GITHUB_WORKSPACE/.rpmmacros $centos:/root/.rpmmacros
        docker exec -i $centos rpmbuild -ba /opt/rpmbuild/SPECS/${{ github.event.inputs.program }}.spec
        
    - name: checkout_rpm
      run: |
        git clone https://github.com/codetiger666/centos_rpms.git

    - name: copy realease
      # 出错继续
      # continue-on-error: true
      run: |
        source $HOME/.profile
        if command -v program_release > /dev/null 2>&1;
        then
          program_release
        fi
        sudo mkdir -p centos_rpms/rocky/9/${{ github.event.inputs.arch }}/
        cd centos_rpms
        git pull
        if [ "${{ github.event.inputs.remove }}" = "true" ];
        then
          rm -f rocky/9/${{ github.event.inputs.arch }}/${{ github.event.inputs.program }}*.${{ github.event.inputs.arch }}.rpm
        fi
        cd ..
        sudo /bin/cp rpm/rpmbuild/RPMS/${{ github.event.inputs.arch }}/${{ github.event.inputs.program }}-${{ github.event.inputs.version }}-1.el9.${{ github.event.inputs.arch }}.rpm centos_rpms/rocky/9/${{ github.event.inputs.arch }}/
        rpms=`docker run -itd -v $(pwd)/centos_rpms:/centos_rpms rockylinux:9`
        docker exec -i $rpms dnf install createrepo -y
        docker exec -i $rpms createrepo /centos_rpms/rocky/9/${{ github.event.inputs.arch }}/ 

    - name: git add
      working-directory: ./centos_rpms
      run: |
        git pull
        git config --local user.email ${{ secrets.email }}
        git config --local user.name "codetiger666"
        # 创建一个新的孤立分支
        git checkout --orphan temp_main
        # 添加所有文件并进行提交
        git add -A
        git commit -m "update"
        # 删除旧的 main 分支并将新分支重命名为 main
        git branch -D main
        git branch -m main
        git remote set-url origin https://${{ secrets.GITHUBTOKEN }}@github.com/codetiger666/centos_rpms.git
        git push -f origin main

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUBTOKEN }}
      with:
        source-directory: 'centos_rpms'
        destination-github-username: 'codetiger666'
        destination-repository-name: 'centos_rpms'
        user-email: ${{ secrets.email }}
        target-branch: main
    
    - name: Remove workflow runs
      uses: GitRML/delete-workflow-runs@main
      if: env.REMOVE_WORKFLOW_RUNS == 'true' && !cancelled()
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: SSH connection to Actions 1
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
